// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_scaled_neg_log_posterior
double Rcpp_scaled_neg_log_posterior(unsigned J, unsigned N, arma::mat SS, arma::vec sigma_G, List param_list, List prior_sd, unsigned n);
RcppExport SEXP _MASSIVE_Rcpp_scaled_neg_log_posterior(SEXP JSEXP, SEXP NSEXP, SEXP SSSEXP, SEXP sigma_GSEXP, SEXP param_listSEXP, SEXP prior_sdSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type J(JSEXP);
    Rcpp::traits::input_parameter< unsigned >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_G(sigma_GSEXP);
    Rcpp::traits::input_parameter< List >::type param_list(param_listSEXP);
    Rcpp::traits::input_parameter< List >::type prior_sd(prior_sdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_scaled_neg_log_posterior(J, N, SS, sigma_G, param_list, prior_sd, n));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_scaled_neg_log_gradient
arma::vec Rcpp_scaled_neg_log_gradient(unsigned J, unsigned N, arma::mat SS, arma::vec sigma_G, List param_list, List prior_sd, unsigned n);
RcppExport SEXP _MASSIVE_Rcpp_scaled_neg_log_gradient(SEXP JSEXP, SEXP NSEXP, SEXP SSSEXP, SEXP sigma_GSEXP, SEXP param_listSEXP, SEXP prior_sdSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type J(JSEXP);
    Rcpp::traits::input_parameter< unsigned >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_G(sigma_GSEXP);
    Rcpp::traits::input_parameter< List >::type param_list(param_listSEXP);
    Rcpp::traits::input_parameter< List >::type prior_sd(prior_sdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_scaled_neg_log_gradient(J, N, SS, sigma_G, param_list, prior_sd, n));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_scaled_neg_log_hessian
arma::mat Rcpp_scaled_neg_log_hessian(unsigned J, unsigned N, arma::mat SS, arma::vec sigma_G, List param_list, List prior_sd, unsigned n);
RcppExport SEXP _MASSIVE_Rcpp_scaled_neg_log_hessian(SEXP JSEXP, SEXP NSEXP, SEXP SSSEXP, SEXP sigma_GSEXP, SEXP param_listSEXP, SEXP prior_sdSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type J(JSEXP);
    Rcpp::traits::input_parameter< unsigned >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_G(sigma_GSEXP);
    Rcpp::traits::input_parameter< List >::type param_list(param_listSEXP);
    Rcpp::traits::input_parameter< List >::type prior_sd(prior_sdSEXP);
    Rcpp::traits::input_parameter< unsigned >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_scaled_neg_log_hessian(J, N, SS, sigma_G, param_list, prior_sd, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MASSIVE_Rcpp_scaled_neg_log_posterior", (DL_FUNC) &_MASSIVE_Rcpp_scaled_neg_log_posterior, 7},
    {"_MASSIVE_Rcpp_scaled_neg_log_gradient", (DL_FUNC) &_MASSIVE_Rcpp_scaled_neg_log_gradient, 7},
    {"_MASSIVE_Rcpp_scaled_neg_log_hessian", (DL_FUNC) &_MASSIVE_Rcpp_scaled_neg_log_hessian, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MASSIVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
