# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp routine for computing the negative log-prior distribution of the MASSIVE model.
#' 
#' @name neg_log_prior
#'
#' @param param_list List of parameter values in Rcpp format.
#' @param prior_sd List of prior standard deviations in Rcpp format.
#'
#' @return numeric value; negative log-prior value for the MASSIVE model.
#' 
#' @keywords internal
NULL

#' Rcpp routine for computing the negative log-posterior distribution of the MASSIVE model.
#'
#' @param J Integer number of genetic instrumental variables.
#' @param N Integer number of observations.
#' @param SS Numeric matrix containing first- and second-order statistics.
#' @param sigma_G Numeric vector of genetic IV standard deviations.
#' @param param_list List of IV model parameter values.
#' @param prior_sd List of standard deviations for the parameter Gaussian priors.
#' @param n Integer number of alleles (trials) for the binomial genetic variants.
#'
#' @return numeric value; negative log-posterior value for the MASSIVE model.
Rcpp_scaled_neg_log_posterior <- function(J, N, SS, sigma_G, param_list, prior_sd, n = 2L) {
    .Call(`_MASSIVE_Rcpp_scaled_neg_log_posterior`, J, N, SS, sigma_G, param_list, prior_sd, n)
}

#' Rcpp routine for computing the negative log-posterior gradient of the MASSIVE model.
#'
#' @param J Integer number of genetic instrumental variables.
#' @param N Integer number of observations.
#' @param SS Numeric matrix containing first- and second-order statistics.
#' @param sigma_G Numeric vector of genetic IV standard deviations.
#' @param param_list List of IV model parameter values.
#' @param prior_sd List of standard deviations for the parameter Gaussian priors.
#' @param n Integer number of alleles (trials) for the binomial genetic variants.
#'
#' @return numeric vector; negative log-posterior gradient for the MASSIVE model.
Rcpp_scaled_neg_log_gradient <- function(J, N, SS, sigma_G, param_list, prior_sd, n = 2L) {
    .Call(`_MASSIVE_Rcpp_scaled_neg_log_gradient`, J, N, SS, sigma_G, param_list, prior_sd, n)
}

#' Rcpp routine for computing the negative log-posterior Hessian of the MASSIVE model.
#'
#' @param J Integer number of genetic instrumental variables.
#' @param N Integer number of observations.
#' @param SS Numeric matrix containing first- and second-order statistics.
#' @param sigma_G Numeric vector of genetic IV standard deviations.
#' @param param_list List of IV model parameter values.
#' @param prior_sd List of standard deviations for the parameter Gaussian priors.
#' @param n Integer number of alleles (trials) for the binomial genetic variants.
#'
#' @return numeric matrix; negative log-posterior Hessian for the MASSIVE model.
Rcpp_scaled_neg_log_hessian <- function(J, N, SS, sigma_G, param_list, prior_sd, n = 2L) {
    .Call(`_MASSIVE_Rcpp_scaled_neg_log_hessian`, J, N, SS, sigma_G, param_list, prior_sd, n)
}

